spring:
  profiles:
    active: prod

#mybatis-plus
mybatis-plus:
  #默认扫描mapper目录
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # 如果查询结果中有空列，则MyBatis在映射的时候，不会映射这个字段
     call-setters-on-nulls: true